server:
  port: 8888

# 配置datasource信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jcx120708
    url: jdbc:mysql://39.108.164.150:3306/shiro_learn?charaterEncoding=UTF-8
    # druid相关配置
    filters: stat,wall
    initialSize: 3
    minIdle: 2
    maxActive: 5
    maxWait: 60000

# 配置视图
  mvc:
    view:
      prefix: /templates/
      suffix: .jsp

# 配置mybatis
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: pro.onlyou.apache.shiro.boot.model

